Add conditions array to OperatorCondition's spec
operator-framework/api pull request #119
Opened 2021-05-10 18:36 UTC by dinhxuanvu

The conditions array in the spec is now available for operator to
create/update as the operator progresses through installation
process. As the spec is updated, the object generation will be
incremented and it can be used for tracking object changes.

Signed-off-by: Vu Dinh <vudinh@outlook.com>

2021-05-13 07:06 UTC, dinhxuanvu commented
The proposal: https://hackmd.io/9wG20hu5TU-y1HrkhvcsZQ?view FYI

2021-05-26 14:28 UTC, awgreene requested changes
Great turn around time on this @dinhxuanvu, left some nits.

2021-05-26 14:28 UTC, awgreene commented on pkg/operators/v2/operatorcondition_types.go
> +// OperatorConditionStatus allows an operator to convey information its state to OLM. The status may trail the actual
```suggestion
// OperatorConditionStatus allows OLM to convey which conditions have been observed.
```

2021-05-26 14:28 UTC, awgreene commented on pkg/operators/v2/operatorcondition_types.go
> +// OperatorConditionSpec allows a cluster admin to convey information about the state of an operator to OLM, potentially overriding state reported by the operator.
```suggestion
// OperatorConditionSpec allows an operator to report state to OLM and provides cluster admin with the ability to manually override state reported by the opeator.
```

2021-05-26 15:12 UTC, dinhxuanvu commented on pkg/operators/v2/operatorcondition_types.go
> +// +kubebuilder:storageversion
Sure.

2021-05-26 15:12 UTC, awgreene commented on pkg/operators/v2/operatorcondition_types.go
> +// cluster admin with the ability to manually override state reported by the operator.
admins
```suggestion
// cluster admins with the ability to manually override state reported by the operator.
```

2021-05-26 15:13 UTC, awgreene requested changes
2 small nits

2021-05-26 15:14 UTC, awgreene commented on pkg/operators/v2/operatorcondition_types.go
> +// cluster admin with the ability to manually override state reported by the operator.
Sorry - this was my suggested mistake haha

2021-05-26 15:35 UTC, awgreene approved these changes

2021-05-26 16:00 UTC, merged

2021-05-27 16:09 UTC, estroz commented
Out of curiosity: why v2 and not v2beta1? Are we confident no significant changes will be needed soon? I feel that it’s a bit hasty to just throw a new stable version out, especially given how short the lifetime of v1 was.

2021-05-27 17:03 UTC, awgreene commented
>Out of curiosity: why v2 and not v2beta1? Are we confident no significant changes will be needed soon? I feel that it’s a bit hasty to just throw a new stable version out, especially given how short the lifetime of v1 was.

Spoke with Eric about this offline, we could have simply added the new fields to v1 but OLM would be unable to identify users that are still writing to the broken v1 API. Additionally, there were concerns that users would rely on a stable (v1)version over a beta/alpha version.