add storage spec to scorecard config
operator-framework/api pull request #135
Opened 2021-06-30 15:47 UTC by fabianvf

(cherry picked from commit e245efd8031e64958764253d6411e6d186911298)

Required for https://github.com/operator-framework/operator-sdk/pull/5028

2021-06-30 15:54 UTC, theishshah commented
/approve

2021-07-01 18:16 UTC, varshaprasad96 approved these changes

2021-07-01 18:31 UTC, jmrodri approved these changes
/lgtm

2021-07-01 21:12 UTC, estroz requested changes

2021-07-01 21:12 UTC, estroz commented on pkg/apis/scorecard/v1alpha3/configuration_types.go
> +	Storage Storage           `json:"storage,omitempty" yaml:"storage,omitempty"`
Fields and type defs need descriptive godocs, since they are the only docs source for this repo right now.

2021-07-02 18:11 UTC, jmrodri approved these changes
/lgtm
/approve

2021-07-02 18:13 UTC, merged