updating dependencies
operator-framework/api pull request #284
Opened 2023-05-25 23:07 UTC by acornett21

- Updating all dependencies to latest
- Updating k8s to 1.27
- Relates: operator-framework/operator-sdk#6381

2023-05-31 16:32 UTC, stevekuznetsov approved these changes

2023-06-26 18:39 UTC, varshaprasad96 requested changes
@acornett21 Thanks for the PR! Can you run `make generate` to update the manifests. Running `make verify` target locally would be helpful in verifying if everything is updated.

2023-06-26 20:36 UTC, varshaprasad96 approved these changes
/lgtm
/approve

2023-06-26 20:59 UTC, grokspawn commented
/approve

2023-06-26 21:03 UTC, merged